telegram:
  token: 1944915470:AAHXDmykhuKzebS6aa6_VntKYDEIgYem7tA      # Telegram bot tokens look like this: 113031530:AAH_4c5Gt9gsVu82OVNjUV7poU7PodYiNsA
  useFirstNameInsteadOfUsername: false
  colonAfterSenderName: false
  skipOldMessages: true
  sendEmojiWithStickers: true
discord:
  useNickname: false
  token: ODczOTAxNDI2NjQyOTM5OTM0.YQ_KIA.cB9hUsfRG1laq7dJgdtFMZ1f0Xs
      # Discord bot tokens look like this: MjI3MDA1NzIvOBQ2MzAzMiMz.DRf-aw.N0MVYtDxXYPSQew4g2TPqvQve2c
  skipOldMessages: true
  replyLength: 100
  maxReplyLines: 2
bridges:
  - name: First bridge
    direction: d2t
    telegram:
      chatId: -1001459932976 # Remember that Telegram group and channel IDs are negative. Include the `-` if you are bridging a group or a channel
      relayJoinMessages: true
      relayLeaveMessages: true
      sendUsernames: true
      relayCommands: true
      crossDeleteOnDiscord: true
    discord:
      channelId: '873884581881864232'       # This ID must be wrapped in single quotes. Example: '244791815503347712'
      relayJoinMessages: true
      relayLeaveMessages: true
      sendUsernames: true
      crossDeleteOnTelegram: true
debug: false
